before_script:
    - echo "HOME = $HOME"
    - echo "NVM_DIR = $NVM_DIR"
    - . "$NVM_DIR/nvm.sh"

yarn-build:
  stage: build
  tags:
    - redshift
  script:
    - yarn

yarn-test:
  stage: test
  tags:
    - redshift
  script:
    - yarn test
    - echo "Success!"
