before_script:
    - /home/user/use_node.sh

yarn-build:
  stage: build
  tags:
    - redshift
  script:
    - yarn

yarn-test:
  stage: test
  tags:
    - redshift
  script:
    - yarn test
    - echo "Success!"
